"""
Curated airport directory for the FareScout UI — lets users pick airports by
city name instead of knowing IATA codes. Covers the world's major commercial
airports plus Google Flights metro codes ("all airports" for multi-airport
cities). Not exhaustive; the AI Agent tab handles anything not listed here.
"""

# (code, label) — label is what users search/see in the dropdown.
AIRPORTS = [
    # Metro codes (Google Flights accepts these as "all airports" for the city)
    ("NYC", "New York, US — All airports (NYC)"),
    ("LON", "London, UK — All airports (LON)"),
    ("PAR", "Paris, FR — All airports (PAR)"),
    ("TYO", "Tokyo, JP — All airports (TYO)"),
    ("ROM", "Rome, IT — All airports (ROM)"),
    ("MIL", "Milan, IT — All airports (MIL)"),
    ("CHI", "Chicago, US — All airports (CHI)"),
    ("WAS", "Washington DC, US — All airports (WAS)"),
    ("SAO", "São Paulo, BR — All airports (SAO)"),
    ("BUE", "Buenos Aires, AR — All airports (BUE)"),
    # United States
    ("ATL", "Atlanta, US — Hartsfield–Jackson (ATL)"),
    ("AUS", "Austin, US — Austin–Bergstrom (AUS)"),
    ("BNA", "Nashville, US — Nashville Intl (BNA)"),
    ("BOS", "Boston, US — Logan Intl (BOS)"),
    ("BWI", "Baltimore, US — Baltimore/Washington Intl (BWI)"),
    ("CLT", "Charlotte, US — Charlotte Douglas (CLT)"),
    ("CVG", "Cincinnati, US — Cincinnati/Northern Kentucky (CVG)"),
    ("DAL", "Dallas, US — Love Field (DAL)"),
    ("DCA", "Washington DC, US — Reagan National (DCA)"),
    ("DEN", "Denver, US — Denver Intl (DEN)"),
    ("DFW", "Dallas–Fort Worth, US — DFW Intl (DFW)"),
    ("DTW", "Detroit, US — Detroit Metro (DTW)"),
    ("EWR", "Newark, US — Newark Liberty (EWR)"),
    ("FLL", "Fort Lauderdale, US — Fort Lauderdale–Hollywood (FLL)"),
    ("HNL", "Honolulu, US — Daniel K. Inouye (HNL)"),
    ("HOU", "Houston, US — Hobby (HOU)"),
    ("IAD", "Washington DC, US — Dulles Intl (IAD)"),
    ("IAH", "Houston, US — George Bush Intercontinental (IAH)"),
    ("IND", "Indianapolis, US — Indianapolis Intl (IND)"),
    ("JFK", "New York, US — John F. Kennedy (JFK)"),
    ("LAS", "Las Vegas, US — Harry Reid Intl (LAS)"),
    ("LAX", "Los Angeles, US — LAX Intl (LAX)"),
    ("LGA", "New York, US — LaGuardia (LGA)"),
    ("MCI", "Kansas City, US — Kansas City Intl (MCI)"),
    ("MCO", "Orlando, US — Orlando Intl (MCO)"),
    ("MDW", "Chicago, US — Midway (MDW)"),
    ("MEM", "Memphis, US — Memphis Intl (MEM)"),
    ("MIA", "Miami, US — Miami Intl (MIA)"),
    ("MSP", "Minneapolis–St. Paul, US — MSP Intl (MSP)"),
    ("MSY", "New Orleans, US — Louis Armstrong (MSY)"),
    ("OAK", "Oakland, US — Oakland Intl (OAK)"),
    ("ORD", "Chicago, US — O'Hare (ORD)"),
    ("PDX", "Portland, US — Portland Intl (PDX)"),
    ("PHL", "Philadelphia, US — Philadelphia Intl (PHL)"),
    ("PHX", "Phoenix, US — Sky Harbor (PHX)"),
    ("PIT", "Pittsburgh, US — Pittsburgh Intl (PIT)"),
    ("RDU", "Raleigh–Durham, US — RDU Intl (RDU)"),
    ("SAN", "San Diego, US — San Diego Intl (SAN)"),
    ("SAT", "San Antonio, US — San Antonio Intl (SAT)"),
    ("SEA", "Seattle, US — Sea–Tac (SEA)"),
    ("SFO", "San Francisco, US — SFO Intl (SFO)"),
    ("SJC", "San Jose, US — Mineta San Jose (SJC)"),
    ("SLC", "Salt Lake City, US — Salt Lake City Intl (SLC)"),
    ("SMF", "Sacramento, US — Sacramento Intl (SMF)"),
    ("STL", "St. Louis, US — Lambert Intl (STL)"),
    ("TPA", "Tampa, US — Tampa Intl (TPA)"),
    # Canada
    ("YEG", "Edmonton, CA — Edmonton Intl (YEG)"),
    ("YHZ", "Halifax, CA — Stanfield Intl (YHZ)"),
    ("YOW", "Ottawa, CA — Macdonald–Cartier (YOW)"),
    ("YUL", "Montreal, CA — Trudeau Intl (YUL)"),
    ("YVR", "Vancouver, CA — Vancouver Intl (YVR)"),
    ("YYC", "Calgary, CA — Calgary Intl (YYC)"),
    ("YYZ", "Toronto, CA — Pearson Intl (YYZ)"),
    # Mexico, Caribbean & Central America
    ("CUN", "Cancún, MX — Cancún Intl (CUN)"),
    ("GDL", "Guadalajara, MX — Guadalajara Intl (GDL)"),
    ("MEX", "Mexico City, MX — Benito Juárez (MEX)"),
    ("MTY", "Monterrey, MX — Monterrey Intl (MTY)"),
    ("PVR", "Puerto Vallarta, MX — Puerto Vallarta Intl (PVR)"),
    ("SJD", "Los Cabos, MX — Los Cabos Intl (SJD)"),
    ("SJO", "San José, CR — Juan Santamaría (SJO)"),
    ("SJU", "San Juan, PR — Luis Muñoz Marín (SJU)"),
    ("PTY", "Panama City, PA — Tocumen Intl (PTY)"),
    ("PUJ", "Punta Cana, DO — Punta Cana Intl (PUJ)"),
    ("MBJ", "Montego Bay, JM — Sangster Intl (MBJ)"),
    ("NAS", "Nassau, BS — Lynden Pindling (NAS)"),
    ("HAV", "Havana, CU — José Martí (HAV)"),
    # South America
    ("BOG", "Bogotá, CO — El Dorado (BOG)"),
    ("EZE", "Buenos Aires, AR — Ezeiza Intl (EZE)"),
    ("GIG", "Rio de Janeiro, BR — Galeão Intl (GIG)"),
    ("GRU", "São Paulo, BR — Guarulhos Intl (GRU)"),
    ("LIM", "Lima, PE — Jorge Chávez (LIM)"),
    ("MDE", "Medellín, CO — José María Córdova (MDE)"),
    ("SCL", "Santiago, CL — Arturo Merino Benítez (SCL)"),
    ("UIO", "Quito, EC — Mariscal Sucre (UIO)"),
    # Europe
    ("AMS", "Amsterdam, NL — Schiphol (AMS)"),
    ("ARN", "Stockholm, SE — Arlanda (ARN)"),
    ("ATH", "Athens, GR — Eleftherios Venizelos (ATH)"),
    ("BCN", "Barcelona, ES — El Prat (BCN)"),
    ("BER", "Berlin, DE — Brandenburg (BER)"),
    ("BRU", "Brussels, BE — Brussels Intl (BRU)"),
    ("BUD", "Budapest, HU — Ferenc Liszt (BUD)"),
    ("CDG", "Paris, FR — Charles de Gaulle (CDG)"),
    ("CPH", "Copenhagen, DK — Kastrup (CPH)"),
    ("DUB", "Dublin, IE — Dublin Intl (DUB)"),
    ("DUS", "Düsseldorf, DE — Düsseldorf Intl (DUS)"),
    ("EDI", "Edinburgh, UK — Edinburgh Intl (EDI)"),
    ("FCO", "Rome, IT — Fiumicino (FCO)"),
    ("FRA", "Frankfurt, DE — Frankfurt Intl (FRA)"),
    ("GVA", "Geneva, CH — Geneva Intl (GVA)"),
    ("HEL", "Helsinki, FI — Vantaa (HEL)"),
    ("IST", "Istanbul, TR — Istanbul Intl (IST)"),
    ("KEF", "Reykjavík, IS — Keflavík (KEF)"),
    ("LGW", "London, UK — Gatwick (LGW)"),
    ("LHR", "London, UK — Heathrow (LHR)"),
    ("LIS", "Lisbon, PT — Humberto Delgado (LIS)"),
    ("LYS", "Lyon, FR — Saint-Exupéry (LYS)"),
    ("MAD", "Madrid, ES — Barajas (MAD)"),
    ("MAN", "Manchester, UK — Manchester Intl (MAN)"),
    ("MRS", "Marseille, FR — Provence (MRS)"),
    ("MUC", "Munich, DE — Franz Josef Strauss (MUC)"),
    ("MXP", "Milan, IT — Malpensa (MXP)"),
    ("NCE", "Nice, FR — Côte d'Azur (NCE)"),
    ("OPO", "Porto, PT — Francisco Sá Carneiro (OPO)"),
    ("ORY", "Paris, FR — Orly (ORY)"),
    ("OSL", "Oslo, NO — Gardermoen (OSL)"),
    ("PRG", "Prague, CZ — Václav Havel (PRG)"),
    ("SVO", "Moscow, RU — Sheremetyevo (SVO)"),
    ("VCE", "Venice, IT — Marco Polo (VCE)"),
    ("VIE", "Vienna, AT — Schwechat (VIE)"),
    ("WAW", "Warsaw, PL — Chopin (WAW)"),
    ("ZRH", "Zurich, CH — Kloten (ZRH)"),
    # Middle East & Africa
    ("AMM", "Amman, JO — Queen Alia (AMM)"),
    ("AUH", "Abu Dhabi, AE — Zayed Intl (AUH)"),
    ("BEY", "Beirut, LB — Rafic Hariri (BEY)"),
    ("CAI", "Cairo, EG — Cairo Intl (CAI)"),
    ("CMN", "Casablanca, MA — Mohammed V (CMN)"),
    ("CPT", "Cape Town, ZA — Cape Town Intl (CPT)"),
    ("DOH", "Doha, QA — Hamad Intl (DOH)"),
    ("DXB", "Dubai, AE — Dubai Intl (DXB)"),
    ("JED", "Jeddah, SA — King Abdulaziz (JED)"),
    ("JNB", "Johannesburg, ZA — O.R. Tambo (JNB)"),
    ("LOS", "Lagos, NG — Murtala Muhammed (LOS)"),
    ("NBO", "Nairobi, KE — Jomo Kenyatta (NBO)"),
    ("RUH", "Riyadh, SA — King Khalid (RUH)"),
    ("TLV", "Tel Aviv, IL — Ben Gurion (TLV)"),
    ("ADD", "Addis Ababa, ET — Bole Intl (ADD)"),
    # Asia
    ("BKK", "Bangkok, TH — Suvarnabhumi (BKK)"),
    ("BLR", "Bengaluru, IN — Kempegowda (BLR)"),
    ("BOM", "Mumbai, IN — Chhatrapati Shivaji (BOM)"),
    ("CGK", "Jakarta, ID — Soekarno–Hatta (CGK)"),
    ("DEL", "Delhi, IN — Indira Gandhi (DEL)"),
    ("HAN", "Hanoi, VN — Noi Bai (HAN)"),
    ("HKG", "Hong Kong — HKG Intl (HKG)"),
    ("HND", "Tokyo, JP — Haneda (HND)"),
    ("ICN", "Seoul, KR — Incheon (ICN)"),
    ("KIX", "Osaka, JP — Kansai (KIX)"),
    ("KUL", "Kuala Lumpur, MY — KLIA (KUL)"),
    ("MNL", "Manila, PH — Ninoy Aquino (MNL)"),
    ("NRT", "Tokyo, JP — Narita (NRT)"),
    ("PEK", "Beijing, CN — Capital Intl (PEK)"),
    ("PVG", "Shanghai, CN — Pudong (PVG)"),
    ("SGN", "Ho Chi Minh City, VN — Tan Son Nhat (SGN)"),
    ("SIN", "Singapore — Changi (SIN)"),
    ("TPE", "Taipei, TW — Taoyuan (TPE)"),
    # Oceania
    ("AKL", "Auckland, NZ — Auckland Intl (AKL)"),
    ("BNE", "Brisbane, AU — Brisbane Intl (BNE)"),
    ("MEL", "Melbourne, AU — Tullamarine (MEL)"),
    ("NAN", "Nadi, FJ — Nadi Intl (NAN)"),
    ("PER", "Perth, AU — Perth Intl (PER)"),
    ("SYD", "Sydney, AU — Kingsford Smith (SYD)"),
]

AIRPORT_LABELS = [label for _, label in AIRPORTS]
LABEL_TO_CODE = {label: code for code, label in AIRPORTS}


def label_for(code: str) -> str:
    """Returns the dropdown label for an IATA code (or the code itself)."""
    for c, label in AIRPORTS:
        if c == code:
            return label
    return code
