"""
Curated airport directory for the FareScout UI — lets users pick airports by
city name instead of knowing IATA codes. Covers the world's major and
secondary commercial airports plus Google Flights metro codes ("all airports"
for multi-airport cities). Not exhaustive; the AI Agent tab handles anything
not listed here.
"""

# (code, label) — label is what users search/see in the dropdown.
AIRPORTS = [
    # Metro codes (Google Flights accepts these as "all airports" for the city)
    ("NYC", "New York, US — All airports (NYC)"),
    ("LON", "London, UK — All airports (LON)"),
    ("PAR", "Paris, FR — All airports (PAR)"),
    ("TYO", "Tokyo, JP — All airports (TYO)"),
    ("ROM", "Rome, IT — All airports (ROM)"),
    ("MIL", "Milan, IT — All airports (MIL)"),
    ("CHI", "Chicago, US — All airports (CHI)"),
    ("WAS", "Washington DC, US — All airports (WAS)"),
    ("SAO", "São Paulo, BR — All airports (SAO)"),
    ("RIO", "Rio de Janeiro, BR — All airports (RIO)"),
    ("BUE", "Buenos Aires, AR — All airports (BUE)"),
    ("MOW", "Moscow, RU — All airports (MOW)"),
    ("SEL", "Seoul, KR — All airports (SEL)"),
    ("OSA", "Osaka, JP — All airports (OSA)"),
    ("BJS", "Beijing, CN — All airports (BJS)"),
    ("STO", "Stockholm, SE — All airports (STO)"),
    ("YTO", "Toronto, CA — All airports (YTO)"),
    # United States
    ("ABQ", "Albuquerque, US — Sunport (ABQ)"),
    ("ALB", "Albany, US — Albany Intl (ALB)"),
    ("ANC", "Anchorage, US — Ted Stevens (ANC)"),
    ("ATL", "Atlanta, US — Hartsfield–Jackson (ATL)"),
    ("AUS", "Austin, US — Austin–Bergstrom (AUS)"),
    ("BDL", "Hartford, US — Bradley Intl (BDL)"),
    ("BHM", "Birmingham, US — Shuttlesworth (BHM)"),
    ("BNA", "Nashville, US — Nashville Intl (BNA)"),
    ("BOI", "Boise, US — Boise Airport (BOI)"),
    ("BOS", "Boston, US — Logan Intl (BOS)"),
    ("BTV", "Burlington, US — Burlington Intl (BTV)"),
    ("BUF", "Buffalo, US — Niagara Intl (BUF)"),
    ("BUR", "Burbank, US — Hollywood Burbank (BUR)"),
    ("BWI", "Baltimore, US — Baltimore/Washington Intl (BWI)"),
    ("CHS", "Charleston, US — Charleston Intl (CHS)"),
    ("CLE", "Cleveland, US — Hopkins Intl (CLE)"),
    ("CLT", "Charlotte, US — Charlotte Douglas (CLT)"),
    ("CMH", "Columbus, US — John Glenn (CMH)"),
    ("CVG", "Cincinnati, US — Cincinnati/Northern Kentucky (CVG)"),
    ("DAL", "Dallas, US — Love Field (DAL)"),
    ("DCA", "Washington DC, US — Reagan National (DCA)"),
    ("DEN", "Denver, US — Denver Intl (DEN)"),
    ("DFW", "Dallas–Fort Worth, US — DFW Intl (DFW)"),
    ("DSM", "Des Moines, US — Des Moines Intl (DSM)"),
    ("DTW", "Detroit, US — Detroit Metro (DTW)"),
    ("ELP", "El Paso, US — El Paso Intl (ELP)"),
    ("EWR", "Newark, US — Newark Liberty (EWR)"),
    ("FLL", "Fort Lauderdale, US — Fort Lauderdale–Hollywood (FLL)"),
    ("GEG", "Spokane, US — Spokane Intl (GEG)"),
    ("GRR", "Grand Rapids, US — Gerald R. Ford (GRR)"),
    ("GSO", "Greensboro, US — Piedmont Triad (GSO)"),
    ("GSP", "Greenville–Spartanburg, US — GSP Intl (GSP)"),
    ("HNL", "Honolulu, US — Daniel K. Inouye (HNL)"),
    ("HOU", "Houston, US — Hobby (HOU)"),
    ("HSV", "Huntsville, US — Huntsville Intl (HSV)"),
    ("IAD", "Washington DC, US — Dulles Intl (IAD)"),
    ("IAH", "Houston, US — George Bush Intercontinental (IAH)"),
    ("IND", "Indianapolis, US — Indianapolis Intl (IND)"),
    ("JAX", "Jacksonville, US — Jacksonville Intl (JAX)"),
    ("JFK", "New York, US — John F. Kennedy (JFK)"),
    ("KOA", "Kona, US — Ellison Onizuka (KOA)"),
    ("LAS", "Las Vegas, US — Harry Reid Intl (LAS)"),
    ("LAX", "Los Angeles, US — LAX Intl (LAX)"),
    ("LGA", "New York, US — LaGuardia (LGA)"),
    ("LGB", "Long Beach, US — Long Beach Airport (LGB)"),
    ("LIH", "Kauai, US — Lihue (LIH)"),
    ("LIT", "Little Rock, US — Clinton National (LIT)"),
    ("MCI", "Kansas City, US — Kansas City Intl (MCI)"),
    ("MCO", "Orlando, US — Orlando Intl (MCO)"),
    ("MDW", "Chicago, US — Midway (MDW)"),
    ("MEM", "Memphis, US — Memphis Intl (MEM)"),
    ("MIA", "Miami, US — Miami Intl (MIA)"),
    ("MKE", "Milwaukee, US — Mitchell Intl (MKE)"),
    ("MSP", "Minneapolis–St. Paul, US — MSP Intl (MSP)"),
    ("MSY", "New Orleans, US — Louis Armstrong (MSY)"),
    ("MYR", "Myrtle Beach, US — Myrtle Beach Intl (MYR)"),
    ("OAK", "Oakland, US — Oakland Intl (OAK)"),
    ("OGG", "Maui, US — Kahului (OGG)"),
    ("OKC", "Oklahoma City, US — Will Rogers (OKC)"),
    ("OMA", "Omaha, US — Eppley Airfield (OMA)"),
    ("ONT", "Ontario, US — Ontario Intl (ONT)"),
    ("ORD", "Chicago, US — O'Hare (ORD)"),
    ("ORF", "Norfolk, US — Norfolk Intl (ORF)"),
    ("PBI", "West Palm Beach, US — Palm Beach Intl (PBI)"),
    ("PDX", "Portland, US — Portland Intl (PDX)"),
    ("PHL", "Philadelphia, US — Philadelphia Intl (PHL)"),
    ("PHX", "Phoenix, US — Sky Harbor (PHX)"),
    ("PIT", "Pittsburgh, US — Pittsburgh Intl (PIT)"),
    ("PNS", "Pensacola, US — Pensacola Intl (PNS)"),
    ("PSP", "Palm Springs, US — Palm Springs Intl (PSP)"),
    ("PVD", "Providence, US — T.F. Green (PVD)"),
    ("PWM", "Portland ME, US — Portland Intl Jetport (PWM)"),
    ("RDU", "Raleigh–Durham, US — RDU Intl (RDU)"),
    ("RIC", "Richmond, US — Richmond Intl (RIC)"),
    ("RNO", "Reno, US — Reno–Tahoe (RNO)"),
    ("ROC", "Rochester, US — Rochester Intl (ROC)"),
    ("RSW", "Fort Myers, US — Southwest Florida Intl (RSW)"),
    ("SAN", "San Diego, US — San Diego Intl (SAN)"),
    ("SAT", "San Antonio, US — San Antonio Intl (SAT)"),
    ("SAV", "Savannah, US — Savannah/Hilton Head (SAV)"),
    ("SDF", "Louisville, US — Muhammad Ali Intl (SDF)"),
    ("SEA", "Seattle, US — Sea–Tac (SEA)"),
    ("SFO", "San Francisco, US — SFO Intl (SFO)"),
    ("SJC", "San Jose, US — Mineta San Jose (SJC)"),
    ("SLC", "Salt Lake City, US — Salt Lake City Intl (SLC)"),
    ("SMF", "Sacramento, US — Sacramento Intl (SMF)"),
    ("SNA", "Orange County, US — John Wayne (SNA)"),
    ("SRQ", "Sarasota, US — Sarasota–Bradenton (SRQ)"),
    ("STL", "St. Louis, US — Lambert Intl (STL)"),
    ("SYR", "Syracuse, US — Hancock Intl (SYR)"),
    ("TPA", "Tampa, US — Tampa Intl (TPA)"),
    ("TUL", "Tulsa, US — Tulsa Intl (TUL)"),
    ("TUS", "Tucson, US — Tucson Intl (TUS)"),
    ("TYS", "Knoxville, US — McGhee Tyson (TYS)"),
    # Canada
    ("YEG", "Edmonton, CA — Edmonton Intl (YEG)"),
    ("YHZ", "Halifax, CA — Stanfield Intl (YHZ)"),
    ("YLW", "Kelowna, CA — Kelowna Intl (YLW)"),
    ("YOW", "Ottawa, CA — Macdonald–Cartier (YOW)"),
    ("YQB", "Quebec City, CA — Jean Lesage (YQB)"),
    ("YQR", "Regina, CA — Regina Intl (YQR)"),
    ("YUL", "Montreal, CA — Trudeau Intl (YUL)"),
    ("YVR", "Vancouver, CA — Vancouver Intl (YVR)"),
    ("YWG", "Winnipeg, CA — Richardson Intl (YWG)"),
    ("YXE", "Saskatoon, CA — Skxwélwen (YXE)"),
    ("YYC", "Calgary, CA — Calgary Intl (YYC)"),
    ("YYJ", "Victoria, CA — Victoria Intl (YYJ)"),
    ("YYT", "St. John's, CA — St. John's Intl (YYT)"),
    ("YYZ", "Toronto, CA — Pearson Intl (YYZ)"),
    # Mexico
    ("ACA", "Acapulco, MX — Juan N. Álvarez (ACA)"),
    ("BJX", "León/Guanajuato, MX — Del Bajío (BJX)"),
    ("CUN", "Cancún, MX — Cancún Intl (CUN)"),
    ("CUU", "Chihuahua, MX — Villalobos Intl (CUU)"),
    ("CZM", "Cozumel, MX — Cozumel Intl (CZM)"),
    ("GDL", "Guadalajara, MX — Guadalajara Intl (GDL)"),
    ("HMO", "Hermosillo, MX — Pesqueira Intl (HMO)"),
    ("HUX", "Huatulco, MX — Bahías de Huatulco (HUX)"),
    ("MEX", "Mexico City, MX — Benito Juárez (MEX)"),
    ("MID", "Mérida, MX — Rejón Intl (MID)"),
    ("MTY", "Monterrey, MX — Monterrey Intl (MTY)"),
    ("MZT", "Mazatlán, MX — Buelna Intl (MZT)"),
    ("OAX", "Oaxaca, MX — Xoxocotlán (OAX)"),
    ("PVR", "Puerto Vallarta, MX — Puerto Vallarta Intl (PVR)"),
    ("QRO", "Querétaro, MX — Querétaro Intl (QRO)"),
    ("SJD", "Los Cabos, MX — Los Cabos Intl (SJD)"),
    ("TIJ", "Tijuana, MX — Tijuana Intl (TIJ)"),
    ("ZIH", "Ixtapa–Zihuatanejo, MX — Ixtapa Intl (ZIH)"),
    # Caribbean & Central America
    ("ANU", "Antigua — V.C. Bird Intl (ANU)"),
    ("AUA", "Aruba — Queen Beatrix (AUA)"),
    ("BDA", "Bermuda — L.F. Wade Intl (BDA)"),
    ("BGI", "Barbados — Grantley Adams (BGI)"),
    ("BZE", "Belize City, BZ — Philip Goldson (BZE)"),
    ("CUR", "Curaçao — Hato Intl (CUR)"),
    ("GCM", "Grand Cayman — Owen Roberts (GCM)"),
    ("GND", "Grenada — Maurice Bishop (GND)"),
    ("GUA", "Guatemala City, GT — La Aurora (GUA)"),
    ("HAV", "Havana, CU — José Martí (HAV)"),
    ("KIN", "Kingston, JM — Norman Manley (KIN)"),
    ("LIR", "Liberia, CR — Guanacaste (LIR)"),
    ("MBJ", "Montego Bay, JM — Sangster Intl (MBJ)"),
    ("MGA", "Managua, NI — Augusto Sandino (MGA)"),
    ("NAS", "Nassau, BS — Lynden Pindling (NAS)"),
    ("PLS", "Providenciales, TC — Turks & Caicos (PLS)"),
    ("POS", "Port of Spain, TT — Piarco Intl (POS)"),
    ("PTY", "Panama City, PA — Tocumen Intl (PTY)"),
    ("PUJ", "Punta Cana, DO — Punta Cana Intl (PUJ)"),
    ("SAL", "San Salvador, SV — Óscar Romero (SAL)"),
    ("SJO", "San José, CR — Juan Santamaría (SJO)"),
    ("SJU", "San Juan, PR — Luis Muñoz Marín (SJU)"),
    ("STT", "St. Thomas, VI — Cyril E. King (STT)"),
    ("SXM", "St. Maarten — Princess Juliana (SXM)"),
    ("UVF", "St. Lucia — Hewanorra Intl (UVF)"),
    # South America
    ("ASU", "Asunción, PY — Silvio Pettirossi (ASU)"),
    ("BAQ", "Barranquilla, CO — Ernesto Cortissoz (BAQ)"),
    ("BOG", "Bogotá, CO — El Dorado (BOG)"),
    ("BRC", "Bariloche, AR — Teniente Candelaria (BRC)"),
    ("BSB", "Brasília, BR — Kubitschek Intl (BSB)"),
    ("CCS", "Caracas, VE — Simón Bolívar (CCS)"),
    ("CLO", "Cali, CO — Alfonso Bonilla (CLO)"),
    ("CNF", "Belo Horizonte, BR — Confins Intl (CNF)"),
    ("COR", "Córdoba, AR — Pajas Blancas (COR)"),
    ("CTG", "Cartagena, CO — Rafael Núñez (CTG)"),
    ("CUZ", "Cusco, PE — Velasco Astete (CUZ)"),
    ("CWB", "Curitiba, BR — Afonso Pena (CWB)"),
    ("EZE", "Buenos Aires, AR — Ezeiza Intl (EZE)"),
    ("FLN", "Florianópolis, BR — Hercílio Luz (FLN)"),
    ("FOR", "Fortaleza, BR — Pinto Martins (FOR)"),
    ("GIG", "Rio de Janeiro, BR — Galeão Intl (GIG)"),
    ("GRU", "São Paulo, BR — Guarulhos Intl (GRU)"),
    ("GYE", "Guayaquil, EC — José Joaquín de Olmedo (GYE)"),
    ("LIM", "Lima, PE — Jorge Chávez (LIM)"),
    ("LPB", "La Paz, BO — El Alto Intl (LPB)"),
    ("MAO", "Manaus, BR — Eduardo Gomes (MAO)"),
    ("MDE", "Medellín, CO — José María Córdova (MDE)"),
    ("MDZ", "Mendoza, AR — El Plumerillo (MDZ)"),
    ("MVD", "Montevideo, UY — Carrasco Intl (MVD)"),
    ("POA", "Porto Alegre, BR — Salgado Filho (POA)"),
    ("REC", "Recife, BR — Guararapes (REC)"),
    ("SCL", "Santiago, CL — Arturo Merino Benítez (SCL)"),
    ("SSA", "Salvador, BR — Magalhães Intl (SSA)"),
    ("UIO", "Quito, EC — Mariscal Sucre (UIO)"),
    ("USH", "Ushuaia, AR — Malvinas Argentinas (USH)"),
    ("VVI", "Santa Cruz, BO — Viru Viru (VVI)"),
    # Western & Northern Europe
    ("AMS", "Amsterdam, NL — Schiphol (AMS)"),
    ("ARN", "Stockholm, SE — Arlanda (ARN)"),
    ("BFS", "Belfast, UK — Belfast Intl (BFS)"),
    ("BGO", "Bergen, NO — Flesland (BGO)"),
    ("BHX", "Birmingham, UK — Birmingham Intl (BHX)"),
    ("BLL", "Billund, DK — Billund Airport (BLL)"),
    ("BOD", "Bordeaux, FR — Mérignac (BOD)"),
    ("BRS", "Bristol, UK — Bristol Airport (BRS)"),
    ("BRU", "Brussels, BE — Brussels Intl (BRU)"),
    ("BSL", "Basel, CH — EuroAirport (BSL)"),
    ("CDG", "Paris, FR — Charles de Gaulle (CDG)"),
    ("CGN", "Cologne, DE — Cologne Bonn (CGN)"),
    ("CPH", "Copenhagen, DK — Kastrup (CPH)"),
    ("CWL", "Cardiff, UK — Cardiff Airport (CWL)"),
    ("DUB", "Dublin, IE — Dublin Intl (DUB)"),
    ("DUS", "Düsseldorf, DE — Düsseldorf Intl (DUS)"),
    ("EDI", "Edinburgh, UK — Edinburgh Intl (EDI)"),
    ("EIN", "Eindhoven, NL — Eindhoven Airport (EIN)"),
    ("FRA", "Frankfurt, DE — Frankfurt Intl (FRA)"),
    ("GLA", "Glasgow, UK — Glasgow Intl (GLA)"),
    ("GOT", "Gothenburg, SE — Landvetter (GOT)"),
    ("GVA", "Geneva, CH — Geneva Intl (GVA)"),
    ("HAJ", "Hannover, DE — Hannover Airport (HAJ)"),
    ("HAM", "Hamburg, DE — Hamburg Airport (HAM)"),
    ("HEL", "Helsinki, FI — Vantaa (HEL)"),
    ("INN", "Innsbruck, AT — Kranebitten (INN)"),
    ("KEF", "Reykjavík, IS — Keflavík (KEF)"),
    ("LBA", "Leeds, UK — Leeds Bradford (LBA)"),
    ("LEJ", "Leipzig, DE — Leipzig/Halle (LEJ)"),
    ("LGW", "London, UK — Gatwick (LGW)"),
    ("LHR", "London, UK — Heathrow (LHR)"),
    ("LIL", "Lille, FR — Lesquin (LIL)"),
    ("LPL", "Liverpool, UK — John Lennon (LPL)"),
    ("LUX", "Luxembourg — Findel (LUX)"),
    ("LYS", "Lyon, FR — Saint-Exupéry (LYS)"),
    ("MAN", "Manchester, UK — Manchester Intl (MAN)"),
    ("MRS", "Marseille, FR — Provence (MRS)"),
    ("MUC", "Munich, DE — Franz Josef Strauss (MUC)"),
    ("NCE", "Nice, FR — Côte d'Azur (NCE)"),
    ("NCL", "Newcastle, UK — Newcastle Intl (NCL)"),
    ("NTE", "Nantes, FR — Atlantique (NTE)"),
    ("NUE", "Nuremberg, DE — Albrecht Dürer (NUE)"),
    ("ORK", "Cork, IE — Cork Airport (ORK)"),
    ("ORY", "Paris, FR — Orly (ORY)"),
    ("OSL", "Oslo, NO — Gardermoen (OSL)"),
    ("RTM", "Rotterdam, NL — The Hague (RTM)"),
    ("SNN", "Shannon, IE — Shannon Airport (SNN)"),
    ("STR", "Stuttgart, DE — Stuttgart Airport (STR)"),
    ("SVG", "Stavanger, NO — Sola (SVG)"),
    ("SXB", "Strasbourg, FR — Entzheim (SXB)"),
    ("SZG", "Salzburg, AT — W.A. Mozart (SZG)"),
    ("TLS", "Toulouse, FR — Blagnac (TLS)"),
    ("TRD", "Trondheim, NO — Værnes (TRD)"),
    ("VIE", "Vienna, AT — Schwechat (VIE)"),
    ("ZRH", "Zurich, CH — Kloten (ZRH)"),
    ("BER", "Berlin, DE — Brandenburg (BER)"),
    # Southern Europe
    ("AGP", "Málaga, ES — Costa del Sol (AGP)"),
    ("ALC", "Alicante, ES — Alicante–Elche (ALC)"),
    ("ATH", "Athens, GR — Eleftherios Venizelos (ATH)"),
    ("BCN", "Barcelona, ES — El Prat (BCN)"),
    ("BIO", "Bilbao, ES — Bilbao Airport (BIO)"),
    ("BLQ", "Bologna, IT — Marconi (BLQ)"),
    ("BRI", "Bari, IT — Karol Wojtyła (BRI)"),
    ("CAG", "Cagliari, IT — Elmas (CAG)"),
    ("CFU", "Corfu, GR — Ioannis Kapodistrias (CFU)"),
    ("CTA", "Catania, IT — Fontanarossa (CTA)"),
    ("FAO", "Faro, PT — Faro Airport (FAO)"),
    ("FCO", "Rome, IT — Fiumicino (FCO)"),
    ("FLR", "Florence, IT — Peretola (FLR)"),
    ("FNC", "Funchal/Madeira, PT — Cristiano Ronaldo (FNC)"),
    ("GOA", "Genoa, IT — Cristoforo Colombo (GOA)"),
    ("HER", "Heraklion/Crete, GR — Kazantzakis (HER)"),
    ("IBZ", "Ibiza, ES — Ibiza Airport (IBZ)"),
    ("JMK", "Mykonos, GR — Mykonos Airport (JMK)"),
    ("JTR", "Santorini, GR — Thira (JTR)"),
    ("LCA", "Larnaca, CY — Glafcos Clerides (LCA)"),
    ("LIS", "Lisbon, PT — Humberto Delgado (LIS)"),
    ("LPA", "Gran Canaria, ES — Las Palmas (LPA)"),
    ("MAD", "Madrid, ES — Barajas (MAD)"),
    ("MLA", "Malta — Luqa (MLA)"),
    ("MXP", "Milan, IT — Malpensa (MXP)"),
    ("NAP", "Naples, IT — Capodichino (NAP)"),
    ("OPO", "Porto, PT — Francisco Sá Carneiro (OPO)"),
    ("PMI", "Palma de Mallorca, ES — Son Sant Joan (PMI)"),
    ("PMO", "Palermo, IT — Falcone–Borsellino (PMO)"),
    ("PSA", "Pisa, IT — Galileo Galilei (PSA)"),
    ("RHO", "Rhodes, GR — Diagoras (RHO)"),
    ("SKG", "Thessaloniki, GR — Makedonia (SKG)"),
    ("SVQ", "Seville, ES — San Pablo (SVQ)"),
    ("TFS", "Tenerife, ES — Tenerife South (TFS)"),
    ("TRN", "Turin, IT — Caselle (TRN)"),
    ("VCE", "Venice, IT — Marco Polo (VCE)"),
    ("VLC", "Valencia, ES — Manises (VLC)"),
    ("VRN", "Verona, IT — Villafranca (VRN)"),
    # Central & Eastern Europe
    ("BEG", "Belgrade, RS — Nikola Tesla (BEG)"),
    ("BTS", "Bratislava, SK — M.R. Štefánik (BTS)"),
    ("BUD", "Budapest, HU — Ferenc Liszt (BUD)"),
    ("DBV", "Dubrovnik, HR — Dubrovnik Airport (DBV)"),
    ("GDN", "Gdańsk, PL — Lech Wałęsa (GDN)"),
    ("KRK", "Kraków, PL — John Paul II (KRK)"),
    ("LJU", "Ljubljana, SI — Jože Pučnik (LJU)"),
    ("OTP", "Bucharest, RO — Henri Coandă (OTP)"),
    ("PRG", "Prague, CZ — Václav Havel (PRG)"),
    ("PRN", "Pristina, XK — Adem Jashari (PRN)"),
    ("RIX", "Riga, LV — Riga Intl (RIX)"),
    ("SJJ", "Sarajevo, BA — Sarajevo Intl (SJJ)"),
    ("SKP", "Skopje, MK — Skopje Intl (SKP)"),
    ("SOF", "Sofia, BG — Vasil Levski (SOF)"),
    ("SPU", "Split, HR — Split Airport (SPU)"),
    ("SVO", "Moscow, RU — Sheremetyevo (SVO)"),
    ("TGD", "Podgorica, ME — Podgorica Airport (TGD)"),
    ("TIA", "Tirana, AL — Nënë Tereza (TIA)"),
    ("TLL", "Tallinn, EE — Lennart Meri (TLL)"),
    ("VNO", "Vilnius, LT — Vilnius Intl (VNO)"),
    ("WAW", "Warsaw, PL — Chopin (WAW)"),
    ("WRO", "Wrocław, PL — Copernicus (WRO)"),
    ("ZAG", "Zagreb, HR — Franjo Tuđman (ZAG)"),
    # Turkey & Caucasus
    ("ADB", "Izmir, TR — Adnan Menderes (ADB)"),
    ("AYT", "Antalya, TR — Antalya Airport (AYT)"),
    ("BJV", "Bodrum, TR — Milas–Bodrum (BJV)"),
    ("DLM", "Dalaman, TR — Dalaman Airport (DLM)"),
    ("ESB", "Ankara, TR — Esenboğa (ESB)"),
    ("EVN", "Yerevan, AM — Zvartnots (EVN)"),
    ("GYD", "Baku, AZ — Heydar Aliyev (GYD)"),
    ("IST", "Istanbul, TR — Istanbul Intl (IST)"),
    ("SAW", "Istanbul, TR — Sabiha Gökçen (SAW)"),
    ("TBS", "Tbilisi, GE — Shota Rustaveli (TBS)"),
    # Middle East
    ("AMM", "Amman, JO — Queen Alia (AMM)"),
    ("AUH", "Abu Dhabi, AE — Zayed Intl (AUH)"),
    ("BAH", "Bahrain — Bahrain Intl (BAH)"),
    ("BEY", "Beirut, LB — Rafic Hariri (BEY)"),
    ("BGW", "Baghdad, IQ — Baghdad Intl (BGW)"),
    ("DMM", "Dammam, SA — King Fahd (DMM)"),
    ("DOH", "Doha, QA — Hamad Intl (DOH)"),
    ("DXB", "Dubai, AE — Dubai Intl (DXB)"),
    ("IKA", "Tehran, IR — Imam Khomeini (IKA)"),
    ("JED", "Jeddah, SA — King Abdulaziz (JED)"),
    ("KWI", "Kuwait City, KW — Kuwait Intl (KWI)"),
    ("MCT", "Muscat, OM — Muscat Intl (MCT)"),
    ("MED", "Medina, SA — Prince Mohammad (MED)"),
    ("RUH", "Riyadh, SA — King Khalid (RUH)"),
    ("TLV", "Tel Aviv, IL — Ben Gurion (TLV)"),
    # Africa
    ("ABJ", "Abidjan, CI — Félix-Houphouët-Boigny (ABJ)"),
    ("ACC", "Accra, GH — Kotoka Intl (ACC)"),
    ("ADD", "Addis Ababa, ET — Bole Intl (ADD)"),
    ("AGA", "Agadir, MA — Al Massira (AGA)"),
    ("ALG", "Algiers, DZ — Houari Boumediene (ALG)"),
    ("CAI", "Cairo, EG — Cairo Intl (CAI)"),
    ("CMN", "Casablanca, MA — Mohammed V (CMN)"),
    ("CPT", "Cape Town, ZA — Cape Town Intl (CPT)"),
    ("DAR", "Dar es Salaam, TZ — Nyerere Intl (DAR)"),
    ("DLA", "Douala, CM — Douala Intl (DLA)"),
    ("DSS", "Dakar, SN — Blaise Diagne (DSS)"),
    ("DUR", "Durban, ZA — King Shaka (DUR)"),
    ("EBB", "Entebbe, UG — Entebbe Intl (EBB)"),
    ("FIH", "Kinshasa, CD — N'djili (FIH)"),
    ("GBE", "Gaborone, BW — Sir Seretse Khama (GBE)"),
    ("HRE", "Harare, ZW — R.G. Mugabe (HRE)"),
    ("JNB", "Johannesburg, ZA — O.R. Tambo (JNB)"),
    ("JRO", "Kilimanjaro, TZ — Kilimanjaro Intl (JRO)"),
    ("KGL", "Kigali, RW — Kigali Intl (KGL)"),
    ("LAD", "Luanda, AO — 4 de Fevereiro (LAD)"),
    ("LOS", "Lagos, NG — Murtala Muhammed (LOS)"),
    ("LUN", "Lusaka, ZM — K.K. Intl (LUN)"),
    ("MBA", "Mombasa, KE — Moi Intl (MBA)"),
    ("MPM", "Maputo, MZ — Maputo Intl (MPM)"),
    ("MRU", "Mauritius — S. Seewoosagur Ramgoolam (MRU)"),
    ("NBO", "Nairobi, KE — Jomo Kenyatta (NBO)"),
    ("RAK", "Marrakech, MA — Menara (RAK)"),
    ("SEZ", "Seychelles — Seychelles Intl (SEZ)"),
    ("TNG", "Tangier, MA — Ibn Battouta (TNG)"),
    ("TNR", "Antananarivo, MG — Ivato (TNR)"),
    ("TUN", "Tunis, TN — Carthage (TUN)"),
    ("VFA", "Victoria Falls, ZW — Victoria Falls Intl (VFA)"),
    ("WDH", "Windhoek, NA — Hosea Kutako (WDH)"),
    ("ZNZ", "Zanzibar, TZ — Abeid Amani Karume (ZNZ)"),
    # South & Central Asia
    ("ALA", "Almaty, KZ — Almaty Intl (ALA)"),
    ("AMD", "Ahmedabad, IN — Sardar Vallabhbhai Patel (AMD)"),
    ("BLR", "Bengaluru, IN — Kempegowda (BLR)"),
    ("BOM", "Mumbai, IN — Chhatrapati Shivaji (BOM)"),
    ("CCU", "Kolkata, IN — Netaji Subhas Chandra Bose (CCU)"),
    ("CMB", "Colombo, LK — Bandaranaike (CMB)"),
    ("COK", "Kochi, IN — Cochin Intl (COK)"),
    ("DAC", "Dhaka, BD — Hazrat Shahjalal (DAC)"),
    ("DEL", "Delhi, IN — Indira Gandhi (DEL)"),
    ("GOI", "Goa, IN — Dabolim (GOI)"),
    ("HYD", "Hyderabad, IN — Rajiv Gandhi (HYD)"),
    ("ISB", "Islamabad, PK — Islamabad Intl (ISB)"),
    ("JAI", "Jaipur, IN — Jaipur Intl (JAI)"),
    ("KHI", "Karachi, PK — Jinnah Intl (KHI)"),
    ("KTM", "Kathmandu, NP — Tribhuvan (KTM)"),
    ("LHE", "Lahore, PK — Allama Iqbal (LHE)"),
    ("MAA", "Chennai, IN — Chennai Intl (MAA)"),
    ("MLE", "Malé, MV — Velana Intl (MLE)"),
    ("NQZ", "Astana, KZ — Nazarbayev Intl (NQZ)"),
    ("PNQ", "Pune, IN — Pune Airport (PNQ)"),
    ("TAS", "Tashkent, UZ — Islam Karimov (TAS)"),
    # East & Southeast Asia
    ("BKI", "Kota Kinabalu, MY — Kota Kinabalu Intl (BKI)"),
    ("BKK", "Bangkok, TH — Suvarnabhumi (BKK)"),
    ("CAN", "Guangzhou, CN — Baiyun Intl (CAN)"),
    ("CEB", "Cebu, PH — Mactan–Cebu (CEB)"),
    ("CGK", "Jakarta, ID — Soekarno–Hatta (CGK)"),
    ("CJU", "Jeju, KR — Jeju Intl (CJU)"),
    ("CKG", "Chongqing, CN — Jiangbei (CKG)"),
    ("CNX", "Chiang Mai, TH — Chiang Mai Intl (CNX)"),
    ("CTS", "Sapporo, JP — New Chitose (CTS)"),
    ("CXR", "Nha Trang, VN — Cam Ranh (CXR)"),
    ("DAD", "Da Nang, VN — Da Nang Intl (DAD)"),
    ("DPS", "Bali, ID — Ngurah Rai (DPS)"),
    ("FUK", "Fukuoka, JP — Fukuoka Airport (FUK)"),
    ("HAN", "Hanoi, VN — Noi Bai (HAN)"),
    ("HGH", "Hangzhou, CN — Xiaoshan (HGH)"),
    ("HKG", "Hong Kong — HKG Intl (HKG)"),
    ("HKT", "Phuket, TH — Phuket Intl (HKT)"),
    ("HND", "Tokyo, JP — Haneda (HND)"),
    ("ICN", "Seoul, KR — Incheon (ICN)"),
    ("KBV", "Krabi, TH — Krabi Intl (KBV)"),
    ("KIX", "Osaka, JP — Kansai (KIX)"),
    ("KMG", "Kunming, CN — Changshui (KMG)"),
    ("KUL", "Kuala Lumpur, MY — KLIA (KUL)"),
    ("LGK", "Langkawi, MY — Langkawi Intl (LGK)"),
    ("MFM", "Macau — Macau Intl (MFM)"),
    ("MNL", "Manila, PH — Ninoy Aquino (MNL)"),
    ("NGO", "Nagoya, JP — Chubu Centrair (NGO)"),
    ("NRT", "Tokyo, JP — Narita (NRT)"),
    ("OKA", "Okinawa, JP — Naha (OKA)"),
    ("PEK", "Beijing, CN — Capital Intl (PEK)"),
    ("PEN", "Penang, MY — Penang Intl (PEN)"),
    ("PNH", "Phnom Penh, KH — Techo Intl (PNH)"),
    ("PQC", "Phu Quoc, VN — Phu Quoc Intl (PQC)"),
    ("PUS", "Busan, KR — Gimhae (PUS)"),
    ("PVG", "Shanghai, CN — Pudong (PVG)"),
    ("RGN", "Yangon, MM — Yangon Intl (RGN)"),
    ("SGN", "Ho Chi Minh City, VN — Tan Son Nhat (SGN)"),
    ("SIN", "Singapore — Changi (SIN)"),
    ("SUB", "Surabaya, ID — Juanda (SUB)"),
    ("SZX", "Shenzhen, CN — Bao'an (SZX)"),
    ("TAO", "Qingdao, CN — Jiaodong (TAO)"),
    ("TFU", "Chengdu, CN — Tianfu (TFU)"),
    ("TPE", "Taipei, TW — Taoyuan (TPE)"),
    ("USM", "Koh Samui, TH — Samui Intl (USM)"),
    ("VTE", "Vientiane, LA — Wattay (VTE)"),
    ("XIY", "Xi'an, CN — Xianyang (XIY)"),
    ("XMN", "Xiamen, CN — Gaoqi (XMN)"),
    # Oceania & Pacific
    ("ADL", "Adelaide, AU — Adelaide Intl (ADL)"),
    ("AKL", "Auckland, NZ — Auckland Intl (AKL)"),
    ("APW", "Apia, WS — Faleolo (APW)"),
    ("BNE", "Brisbane, AU — Brisbane Intl (BNE)"),
    ("CBR", "Canberra, AU — Canberra Intl (CBR)"),
    ("CHC", "Christchurch, NZ — Christchurch Intl (CHC)"),
    ("CNS", "Cairns, AU — Cairns Intl (CNS)"),
    ("DRW", "Darwin, AU — Darwin Intl (DRW)"),
    ("GUM", "Guam — Antonio B. Won Pat (GUM)"),
    ("HBA", "Hobart, AU — Hobart Intl (HBA)"),
    ("MEL", "Melbourne, AU — Tullamarine (MEL)"),
    ("NAN", "Nadi, FJ — Nadi Intl (NAN)"),
    ("NOU", "Nouméa, NC — La Tontouta (NOU)"),
    ("OOL", "Gold Coast, AU — Gold Coast Airport (OOL)"),
    ("PER", "Perth, AU — Perth Intl (PER)"),
    ("POM", "Port Moresby, PG — Jacksons Intl (POM)"),
    ("PPT", "Tahiti, PF — Faa'a Intl (PPT)"),
    ("RAR", "Rarotonga, CK — Rarotonga Intl (RAR)"),
    ("SYD", "Sydney, AU — Kingsford Smith (SYD)"),
    ("WLG", "Wellington, NZ — Wellington Intl (WLG)"),
    ("ZQN", "Queenstown, NZ — Queenstown Intl (ZQN)"),
]

AIRPORT_LABELS = [label for _, label in AIRPORTS]
LABEL_TO_CODE = {label: code for code, label in AIRPORTS}


def label_for(code: str) -> str:
    """Returns the dropdown label for an IATA code (or the code itself)."""
    for c, label in AIRPORTS:
        if c == code:
            return label
    return code
